DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS motion_picture_association;
DROP TABLE IF EXISTS users;

CREATE TABLE genres (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_name VARCHAR(255)
);

CREATE TABLE films (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  description VARCHAR(1000),
  release_date DATE,
  duration INTEGER,
  mpa_id INTEGER
);

CREATE TABLE motion_picture_association (
  mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mpa_name VARCHAR(255)
);

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255),
  login VARCHAR(255),
  name VARCHAR(255),
  birthday DATE
);

CREATE TABLE film_genres (
  film_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE likes (
  film_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  like_timestamp TIMESTAMP,
  PRIMARY KEY (film_id, user_id)
);

CREATE TABLE friends (
  user_id INTEGER NOT NULL,
  friend_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, friend_id)
);

ALTER TABLE film_genres ADD CONSTRAINT fk_film_genres_film_id FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE;
ALTER TABLE film_genres ADD CONSTRAINT fk_film_genres_genre_id FOREIGN KEY (genre_id) REFERENCES genres (genre_id) ON DELETE CASCADE;

ALTER TABLE films ADD CONSTRAINT fk_films_mpa_id FOREIGN KEY (mpa_id) REFERENCES motion_picture_association (mpa_id) ON DELETE CASCADE;

ALTER TABLE likes ADD CONSTRAINT fk_likes_film_id FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE;
ALTER TABLE likes ADD CONSTRAINT fk_likes_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE friends ADD CONSTRAINT fk_friends_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;
ALTER TABLE friends ADD CONSTRAINT fk_friends_friend_id FOREIGN KEY (friend_id) REFERENCES users (user_id) ON DELETE CASCADE;